/** Классы из globals.css — сплошные цвета, без прозрачности */
export const adminClass = {
  panel: "admin-panel p-4",
  sidebar: "admin-sidebar",
  navLink: "admin-nav-link",
  navLinkActive: "admin-nav-link-active",
  btnPrimary: "admin-btn admin-btn-primary",
  btnSecondary: "admin-btn admin-btn-secondary",
  btnSmOn: "admin-btn-sm admin-btn-sm-on",
  btnSmOff: "admin-btn-sm admin-btn-sm-off",
  link: "admin-link",
  textLink: "admin-text-link",
  code: "admin-code",
  badgeRunning: "admin-badge admin-badge-running",
  badgeDone: "admin-badge admin-badge-done",
  badgeError: "admin-badge admin-badge-error",
  badgeIdle: "admin-badge admin-badge-idle",
  alertError: "admin-alert-error",
  alertSuccess: "admin-alert-success",
  progressTrack: "admin-progress-track",
  progressFill: "admin-progress-fill",
  tableHead: "admin-table-head",
  tableRow: "admin-table-row",
  statLabel: "admin-stat-label",
  statValue: "admin-stat-value",
  input: "site-input",
} as const;
